version: "1"

services:
  # 1. API Gateway
  - type: web
    name: aerocommerce-api-gateway
    env: docker
    dockerfilePath: ./src/AeroCommerce.ApiGateway/Dockerfile
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000
      # (Nên điền JWT_SECRET trong Render Dashboard)

  # 2. User Service
  - type: web
    name: aerocommerce-user-service
    env: docker
    dockerfilePath: ./src/AeroCommerce.UserService/Dockerfile
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000
      - key: DATABASE_URL
        sync: false # Báo cho Render biết bạn sẽ tự nhập ở Dashboard

  # 3. Post Service
  - type: web
    name: aerocommerce-post-service
    env: docker
    dockerfilePath: ./src/AeroCommerce.PostService/Dockerfile
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000
      - key: DATABASE_URL
        sync: false

  # 4. Product Service
  - type: web
    name: aerocommerce-product-service
    env: docker
    dockerfilePath: ./src/AeroCommerce.ProductService/Dockerfile
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000
      - key: DATABASE_URL
        sync: false

  # 5. Cart Service
  - type: web
    name: aerocommerce-cart-service
    env: docker
    dockerfilePath: ./src/AeroCommerce.CartService/Dockerfile
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000
      - key: DATABASE_URL
        sync: false

  # 6. Order Service
  - type: web
    name: aerocommerce-order-service
    env: docker
    dockerfilePath: ./src/AeroCommerce.OrderService/Dockerfile
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:10000
      - key: DATABASE_URL
        sync: false
