[build]
builder = "DOCKERFILE"
dockerfilePath = "src/AeroCommerce.UserService/Dockerfile"

[deploy]
startCommand = "dotnet AeroCommerce.UserService.dll"
healthcheckPath = "/health"
restartPolicyType = "on_failure"
