[build]
builder = "DOCKERFILE"
dockerfilePath = "src/CodePulse.PostService/Dockerfile"

[deploy]
startCommand = "dotnet CodePulse.PostService.dll"
healthcheckPath = "/health"
restartPolicyType = "on_failure"
